import type { Metadata } from "next";
import { Inter } from "next/font/google";

import ToastProvider from '@/components/ToastProvider'
import Navbar from "@/components/global/Navbar";
import NavHeader from "@/components/NavHeader";
import Footer from "@/components/global/Footer";
import Container from "@/components/global/Container";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (

        <ToastProvider>
            <NavHeader />
            <Navbar />
            <Container>
                <div className="min-h-[80vh]">
                    {children}
                </div>
                <Footer />
            </Container>

        </ToastProvider>
    );
}
